node_latent_dim: 50
dimenet_hidden_channels: 256
dimenet_num_blocks: 6
dimenet_int_emb_size: 64
dimenet_basis_emb_size: 8
dimenet_out_emb_channels: 256
dimenet_num_spherical: 7
dimenet_num_radial: 6
dimenet_max_num_neighbors: 32
dimenet_envelope_exponent: 5
dimenet_num_before_skip: 1
dimenet_num_after_skip: 2
dimenet_num_output_layers: 3
cutoff: 5.0
do_postprocessing: true

scaler:
  scale_: 0.870582896669776
  mean_: -7.349405628928332