hidden_channels: 128
num_layers: 3
num_rbf: 50
cutoff: 5.0
max_neighbors: 50
rbf:
  name: "spherical_bessel"
envelope:
  name: "polynomial"
  exponent: 5
regress_forces: true
direct_forces: true
use_pbc: false
otf_graph: true
num_elements: 100